version: '3.2'
services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: .dev.dockerfile
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./backend
        target: /code
    ports:
      - 4000:4000
      - 4001:5432
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: .dev.dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /code
    ports:
      - 3000:3000
