version: '3.2'
services:
  db-dev:
    restart: always
    image: postgres:12.1
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/data
    network_mode: service:frontend-dev
  backend-dev:
    build:
      context: ./trello_api
      dockerfile: .dev.dockerfile
    volumes:
      - type: bind
        source: ./trello_api
        target: /code
    network_mode: service:frontend-dev
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: .dev.dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /code
    ports:
      - 3000:3000
      - 4000:4000
      - 5432:5432
